name: dating_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0-179.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  step_progress_indicator: ^1.0.2
  intl: ^0.18.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.2
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Optima
      fonts:
        - asset: fonts/OPN.TTF